Repository lblod/notulen-prepublish-service, pull requests merged in 2021-08, with the labels that each got.

#56 Add release-it config
  package-lock.json
  package.json
  release-it.json
Labels: internal

#55 Use a job for a pre-publishing
  routes/preview.js
Labels: bug, enhancement

#58 validation error on treatment preview
  README.md
  routes/preview.js
Labels: enhancement

#61 Implement task flow for notulen
  models/task.js
  routes/preview.js
  routes/publication.js
  routes/signing.js
  support/task-utils.js
Labels: enhancement
